export const personal_events = [
	{
		id: 1,
		thumbnail: 'images/event1.png',
		title: 'Climate advocate training module 5: nurturing the grassroots',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Monday, May 2, 2002',
		time: '5:30 PM PST',
		limit: 100,
		org: "Citizens' Climate Lobby",
		location: 'San Fernando, Cebu',
		quests: ['Kill a slime.   0/5', 'Eat a banana.   0/5'],
		badges: ['Gooey Person', 'Banana Warrior'],
		status: false,
		xp: 100000,
	},
	{
		id: 2,
		thumbnail: 'images/event2.png',
		title: "Mediator's Green Pledge Earth Day event",
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Friday, Apr 29, 2022',
		time: '5:30 PM PST',
		limit: 100,
		org: 'World Alliance of Mediators Against Climate Change',
		status: true,
		xp: 156000,
	},
	{
		id: 3,
		thumbnail: 'images/event3.png',
		title: 'Care homes during Covid: Connection and closeness',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Thursday, Apr 28, 2022',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Bristol Research Forum on Ageing',
		status: false,
		xp: 456902,
	},
	{
		id: 4,
		thumbnail: 'images/event4.png',
		title:
			'Food for the Rest of Us - Decolonizing Urban Foodscapes Panel Discussion',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Friday, Apr 29, 2022',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Fresh Roots',
		status: true,
		xp: 126000,
	},
	{
		id: 5,
		thumbnail: 'images/event5.png',
		title: 'New Volunteer Orientation 2022 Virtual Event',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Tuesday, May 10, 2022',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Heal the Bay',
		status: false,
		xp: 356000,
	},
	{
		id: 6,
		thumbnail: 'images/event6.png',
		title: '2022 State of Homelessness Conference',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Thusday, Apr 28, 2022',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Coalition for the Homeless of Houston',
		status: false,
		xp: 67000,
	},
	{
		id: 7,
		thumbnail: 'images/event7.png',
		title: 'Climate Careers Fair',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Saturday, Apr 30, 2022',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Black Mountains College',
		status: true,
		xp: 55902,
	},
	{
		id: 8,
		thumbnail: 'images/event8.png',
		title: '2022 United Nations World Oceans Day Event',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Wednesday, June 8, 2022',
		time: '5:30 PM PST',
		limit: 100,
		org: 'United Nations DOALOS',
		status: false,
		xp: 210000,
	},
	{
		id: 9,
		thumbnail: 'images/event2.png',
		title: 'Climate advocate training module 5: nurturing the grassroots v2',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Monday, May 2, 2003',
		time: '5:30 PM PST',
		limit: 100,
		org: "Citizens' Climate Lobby",
		status: false,
		xp: 5000,
	},
	{
		id: 10,
		thumbnail: 'images/event4.png',
		title: "Mediator's Green Pledge Earth Day event v2",
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Friday, Apr 29, 2023',
		time: '5:30 PM PST',
		limit: 100,
		org: 'World Alliance of Mediators Against Climate Change',
		status: false,
		xp: 8500,
	},
	{
		id: 11,
		thumbnail: 'images/event6.png',
		title: 'Care homes during Covid: Connection and closeness v2',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Thursday, Apr 28, 2023',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Bristol Research Forum on Ageing',
		status: false,
		xp: 140000,
	},
	{
		id: 12,
		thumbnail: 'images/event8.png',
		title:
			'Food for the Rest of Us - Decolonizing Urban Foodscapes Panel Discussion v2',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Friday, Apr 29, 2023',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Fresh Roots',
		status: false,
		xp: 34000,
	},
	{
		id: 13,
		thumbnail: 'images/event1.png',
		title: 'New Volunteer Orientation 2022 Virtual Event v2',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Tuesday, May 10, 2023',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Heal the Bay',
		status: true,
		xp: 678000,
	},
	{
		id: 14,
		thumbnail: 'images/event3.png',
		title: '2022 State of Homelessness Conference v2',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Thursday, Apr 28, 2023',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Coalition for the Homeless of Houston',
		status: false,
		xp: 14000,
	},
	{
		id: 15,
		thumbnail: 'images/event5.png',
		title: 'Climate Careers Fair v2',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Saturday, Apr 30, 2023',
		time: '5:30 PM PST',
		limit: 100,
		org: 'Black Mountains College',
		status: false,
		xp: 25000,
	},
	{
		id: 16,
		thumbnail: 'images/event7.png',
		title: '2022 United Nations World Oceans Day Event v2',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
		date: 'Wednesday, June 8, 2023',
		time: '5:30 PM PST',
		limit: 100,
		org: 'United Nations DOALOS',
		status: true,
		xp: 69000,
	},
];
