export const events = [
	{
		id: 1,
		thumbnail: 'images/event1.png',
		organizer: 'CIT-U',
		title: 'Climate advocate training module 5: nurturing the grassroots',
		date: 'Mon, May 2, 2002 5:30 PM PST',
		time: '5:30 PM PST',
		org: "Citizens' Climate Lobby",
		location: 'San Fernando, Cebu',
		quests: ['Kill a slime.   0/5', 'Eat a banana.   0/5'],
		badges: ['Gooey Person', 'Banana Warrior'],
		xp: 100000,
	},
	{
		id: 2,
		thumbnail: 'images/event2.png',
		title: "Mediator's Green Pledge Earth Day event",
		date: 'Fri, Apr 29, 2022 1:30 PM PST',
		org: 'World Alliance of Mediators Against Climate Change',
		xp: 156000,
	},
	{
		id: 3,
		thumbnail: 'images/event3.png',
		title: 'Care homes during Covid: Connection and closeness',
		date: 'Thu, Apr 28, 2022 9:00PM PST',
		org: 'Bristol Research Forum on Ageing',
		xp: 456902,
	},
	{
		id: 4,
		thumbnail: 'images/event4.png',
		title:
			'Food for the Rest of Us - Decolonizing Urban Foodscapes Panel Discussion',
		date: 'Fri, Apr 29, 2022 10:00 AM PST',
		org: 'Fresh Roots',
		xp: 126000,
	},
	{
		id: 5,
		thumbnail: 'images/event5.png',
		title: 'New Volunteer Orientation 2022 Virtual Event',
		date: 'Tue, May 10, 2022 9:30 AM PST',
		org: 'Heal the Bay',
		xp: 356000,
	},
	{
		id: 6,
		thumbnail: 'images/event6.png',
		title: '2022 State of Homelessness Conference',
		date: 'Thu, Apr 28, 2022 9:30 PM PST',
		org: 'Coalition for the Homeless of Houston',
		xp: 67000,
	},
	{
		id: 7,
		thumbnail: 'images/event7.png',
		title: 'Climate Careers Fair',
		date: 'Sat, Apr 30, 2022 5:00 PM PST',
		org: 'Black Mountains College',
		xp: 55902,
	},
	{
		id: 8,
		thumbnail: 'images/event8.png',
		title: '2022 United Nations World Oceans Day Event',
		date: 'Wed, June 8, 2022 10:00 PM PST',
		org: 'United Nations DOALOS',
		xp: 210000,
	},
	{
		id: 9,
		thumbnail: 'images/event2.png',
		title: 'Climate advocate training module 5: nurturing the grassroots v2',
		date: 'Mon, May 2, 2003 5:30 PM PST',
		org: "Citizens' Climate Lobby",
		xp: 5000,
	},
	{
		id: 10,
		thumbnail: 'images/event4.png',
		title: "Mediator's Green Pledge Earth Day event v2",
		date: 'Fri, Apr 29, 2023 1:30 PM PST',
		org: 'World Alliance of Mediators Against Climate Change',
		xp: 8500,
	},
	{
		id: 11,
		thumbnail: 'images/event6.png',
		title: 'Care homes during Covid: Connection and closeness v2',
		date: 'Thu, Apr 28, 2023 9:00PM PST',
		org: 'Bristol Research Forum on Ageing',
		xp: 140000,
	},
	{
		id: 12,
		thumbnail: 'images/event8.png',
		title:
			'Food for the Rest of Us - Decolonizing Urban Foodscapes Panel Discussion v2',
		date: 'Fri, Apr 29, 2023 10:00 AM PST',
		org: 'Fresh Roots',
		xp: 34000,
	},
	{
		id: 13,
		thumbnail: 'images/event1.png',
		title: 'New Volunteer Orientation 2022 Virtual Event v2',
		date: 'Tue, May 10, 2023 9:30 AM PST',
		org: 'Heal the Bay',
		xp: 678000,
	},
	{
		id: 14,
		thumbnail: 'images/event3.png',
		title: '2022 State of Homelessness Conference v2',
		date: 'Thu, Apr 28, 2023 9:30 PM PST',
		org: 'Coalition for the Homeless of Houston',
		xp: 14000,
	},
	{
		id: 15,
		thumbnail: 'images/event5.png',
		title: 'Climate Careers Fair v2',
		date: 'Sat, Apr 30, 2023 5:00 PM PST',
		org: 'Black Mountains College',
		xp: 25000,
	},
	{
		id: 16,
		thumbnail: 'images/event7.png',
		title: '2022 United Nations World Oceans Day Event v2',
		date: 'Wed, June 8, 2023 10:00 PM PST',
		org: 'United Nations DOALOS',
		xp: 69000,
	},
];
