export const profiles = [
	{
		id: 1,
		image: '',
		name: 'Nash Uriel A. Tapayan',
		username: 'taps-nash',
		email: 'tnashuriel@gmail.com',
		isOrganizer: true,
		organization: 'Peer Mentors Club',
	},
	{
		id: 2,
		image: 'images/profile2.png',
		name: 'Mervin John C. Tampus',
		username: 'desolate',
		email: 'j.desolate53@gmail.com',
		isOrganizer: false,
		organization: '',
	},
	{
		id: 3,
		image: 'images/profile3.png',
		name: 'Jezreel Jedidiah O. Floreta',
		username: 'cyberblaze',
		email: 'cyberblazeflo7@gmail.com',
		isOrganizer: false,
		organization: '',
	},
	{
		id: 4,
		image: '',
		name: 'Renz Brian T. Velez',
		username: 'zenshi',
		email: 'velezrenz@gmail.com',
		isOrganizer: true,
		organization: 'ICPEP',
	},
	{
		id: 5,
		image: 'images/profile5.png',
		name: 'Jessa Marie Macapagong',
		username: 'sw8potato',
		email: 'jessamacapagong00@gmail.com',
		isOrganizer: false,
		organization: '',
	},
];
